annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - bump version of VM components to [v1.143.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.143.0)
    - fix Alertmanager templates path to match VM Operator mount. See [#2883](https://github.com/VictoriaMetrics/helm-charts/pull/2883).
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/victoriametrics/
    - name: Changelog
      url: https://docs.victoriametrics.com/victoriametrics/changelog/
  artifacthub.io/operator: "true"
  artifacthub.io/readme: |
    # VictoriaMetrics K8s Stack Helm chart

    Chart documentation is available [here](https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack/).
    Changelog is [here](https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack/changelog/).
apiVersion: v2
appVersion: v1.143.0
dependencies:
- name: victoria-metrics-common
  repository: oci://ghcr.io/victoriametrics/helm-charts
  version: 0.3.*
- condition: victoria-metrics-operator.enabled
  name: victoria-metrics-operator
  repository: oci://ghcr.io/victoriametrics/helm-charts
  version: 0.62.*
- condition: kube-state-metrics.enabled
  name: kube-state-metrics
  repository: oci://ghcr.io/prometheus-community/charts
  version: 7.3.*
- condition: prometheus-node-exporter.enabled
  name: prometheus-node-exporter
  repository: oci://ghcr.io/prometheus-community/charts
  version: 4.53.*
- condition: grafana.enabled
  name: grafana
  repository: oci://ghcr.io/grafana-community/helm-charts
  version: 12.2.*
description: Kubernetes monitoring on VictoriaMetrics stack. Includes VictoriaMetrics
  Operator, Grafana dashboards, ServiceScrapes and VMRules
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- operator
- monitoring
- kubernetes
- observability
- tsdb
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-k8s-stack
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.78.0
